spring:
  redis:
    host: 127.0.0.1

  datasource:
    url: jdbc:mysql://localhost:3306/shorturl?useSSL=false
    username: root
    password: 123456

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
